Training/MVC/Day3Assignment/Day3Assignment/Models/ErrorViewModel.cs
using System;

namespace Day3Assignment.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Training/MVC/Day3Assignment/Day3Assignment/Models/MyDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Data.Entity;

namespace Day3Assignment.Models
{
    public class MyDbContext
    {
        public MyDbContext(): base()

        {

        }

        public DbSet<User> Users { get; set; }
    }
}

Training/MVC/Day3Assignment/Day3Assignment/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Day3Assignment.Models
{
    public class User
    {
        
        

            [Key]

            [DatabaseGenerated(DatabaseGeneratedOption.None)]

            public string UserName { get; set; }

            public string Password { get; set; }

        }
    }

Training/MVC/Day3Assignment/Day3Assignment/Controllers/Home1Controller.cs
using Day3Assignment.Models;
using Grpc.Core;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Web;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;


namespace Day3Assignment.Controllers
{
    public class Home1Controller : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        public Home1Controller(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            ViewData["str1"] = "This is a string passed using ViewData";

            ViewData["num1"] = 100;

            ViewBag.str2 = "This is a string passed using ViewBag";

            ViewBag.num2 = 200;

            return View();
        }

        public ActionResult AddUser()

        {

            return View();

        }
      
        public ActionResult SaveUser(User u)

        {
            string ContentRootPath = _webHostEnvironment.ContentRootPath;
            string path = Path.Combine(ContentRootPath, @"App_Data/users.txt");

             
            StreamWriter sw = new StreamWriter(path, true);

            sw.WriteLine("User details added on: " + DateTime.Now.ToString());

            sw.WriteLine("User name: " + u.UserName);

            sw.WriteLine("Password: " + u.Password);

            sw.WriteLine();

            sw.Close();

            return Content("User details have been saved");

        }

        public ActionResult HtmlHelpers()

        {

            return View();

        }
    }
}

Training/MVC/Day3Assignment/Day3Assignment/Controllers/HomeController.cs
using Day3Assignment.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Day3Assignment.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Training/MVC/Day3Assignment/Day3Assignment/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Day3Assignment.Data;
using Day3Assignment.Models;

namespace Day3Assignment.Controllers
{
    public class UsersController : Controller
    {
        private readonly Day3AssignmentContext _context;

        public UsersController(Day3AssignmentContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.User.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.UserName == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserName,Password")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("UserName,Password")] User user)
        {
            if (id != user.UserName)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserName))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.UserName == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _context.User.FindAsync(id);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(string id)
        {
            return _context.User.Any(e => e.UserName == id);
        }
    }
}

Training/MVC/Day3Assignment/Day3Assignment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Training/MVC/Day3Assignment/Day3Assignment/Views/Home1/AddUser.cshtml
@model User
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using (Html.BeginForm("SaveUser", "Home1"))

{

    <p>

        @Html.TextBoxFor(user => user.UserName)



    </p>

    <p>

        @Html.PasswordFor(user => user.Password)

    </p>

    <input type="submit" value="Add User" />

}

Training/MVC/Day3Assignment/Day3Assignment/Views/Home1/HtmlHelpers.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@using (Html.BeginForm())

{

    <p>

        Textbox: @Html.TextBox("textbox1")

    </p>

    <p>

        Textarea: @Html.TextArea("textarea1")

    </p>

    string[] s = { "Option1", "Option2", "Option3" };

    SelectList list = new SelectList(s);

    <p>

        Dropdown: @Html.DropDownList("dropdownlist1", list,

"SELECT")

    </p>

    <p>

        Listbox: @Html.ListBox("listbox1", list)

    </p>

    <p>

        Radio Buttons:<br />

        @Html.RadioButton("radiobutton", "RadioButton1")

        RadioButton1

        @Html.RadioButton("radiobutton", "RadioButton2")

        RadioButton2

        @Html.RadioButton("radiobutton", "RadioButton3")

        RadioButton3

    </p>

    <p>

        Checkboxes:<br />

        @Html.CheckBox("checkbox1", true) CheckBox1 (initially

        checked)

        @Html.CheckBox("checkbox2") CheckBox2

        @Html.CheckBox("checkbox3") CheckBox3

    </p>

    <p>

        Hyperlink: @Html.ActionLink("Back to home", "Index")

    </p>

    <input type="submit" value="Submit" />

}

@section localcontent

{

<h3>HtmlHelpers.cshtml's local content goes here</h3>

}

Training/MVC/Day3Assignment/Day3Assignment/Views/Home1/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Data passed using ViewData</h1>

@{

    string str1 = (string)ViewData["str1"];

    int num1 = (int)ViewData["num1"];

    <h3>@str1</h3>

    <h3>@num1</h3>

}

<h1>Data passed using ViewBag</h1>

@{

    string str2 = ViewBag.str2;

    int num2 = ViewBag.num2;

    <h3>@str2</h3>

    <h3>@num2</h3>

}

@section localcontent

{

    <h3>Index.cshtml's local content goes here</h3>

}

Training/MVC/Day3Assignment/Day3Assignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Day3Assignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Day3Assignment</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <hr />

            <i>This is the header (Common Content)</i>

            @RenderSection("localcontent", false)

            <hr />
            @RenderBody()
            <hr />

            <i>This is the footer (Common Content)</i>

            <hr />
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Day3Assignment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Training/MVC/Day3Assignment/Day3Assignment/Views/Users/Create.cshtml
@model Day3Assignment.Models.User

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Training/MVC/Day3Assignment/Day3Assignment/Views/Users/Delete.cshtml
@model Day3Assignment.Models.User

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="UserName" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Training/MVC/Day3Assignment/Day3Assignment/Views/Users/Details.cshtml
@model Day3Assignment.Models.User

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.UserName">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Training/MVC/Day3Assignment/Day3Assignment/Views/Users/Edit.cshtml
@model Day3Assignment.Models.User

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UserName" />
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Training/MVC/Day3Assignment/Day3Assignment/Views/Users/Index.cshtml
@model IEnumerable<Day3Assignment.Models.User>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.UserName">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.UserName">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.UserName">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>